[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "chemfunctions"
version = "0.0.1"
description = "Utilities for using quantum chemistry to design electrolyte molecules"
requires-python = ">=3.10"

